version: "3"
networks:
  app-tier:
    driver: bridge

services:
  serviceregistry:
    build:
      context: ./service-registry  
    container_name: serviceregistry
    ports:
      - "8761:8761"
    networks:
      - app-tier

  configserver:
    build:
      context: ./configserver  
    container_name: configserver
    depends_on:
      - serviceregistry
    ports:
      - "9296:9296"  
    environment:
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
    restart: "no"
    networks:
      - app-tier

  mysql:
    image: 'mysql'
    container_name: mysql
    restart: unless-stopped
    networks:
      - app-tier
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdb
    ports:
      - '3306:3306'

  apigateway:
    build:
      context: ./apigateway
    container_name: apigateway
    ports:
      - "9090:9090"
    depends_on:
      - serviceregistry
      - configserver
    environment:
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
      CONFIG_SERVER_ADDRESS: http://configserver:9296
    restart: "no"
    networks:
      - app-tier

  authservice:
    build:
      context: ./auth-service  
    container_name: authservice
    depends_on:
      - serviceregistry
      - apigateway
      - configserver
    ports:
      - "7777:7777"
    environment:
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
      CONFIG_SERVER_ADDRESS: http://configserver:9296
      DB_HOST: mysql
    restart: "no"
    networks:
      - app-tier

  productservice:
    build:
      context: ./productservice
    container_name: productservice
    depends_on:
      - serviceregistry
      - apigateway
      - authservice
      - configserver
      - mysql
    ports:
      - "8081:8081"
    environment:
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
      CONFIG_SERVER_ADDRESS: http://configserver:9296
      DB_HOST: mysql
    restart: "no"
    networks:
      - app-tier

  orderservice:
    build:
      context: ./orderservice  
    container_name: orderservice
    depends_on:
      - serviceregistry
      - apigateway
      - authservice
      - configserver
      - mysql
    ports:
      - "8082:8082"
    environment:
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
      CONFIG_SERVER_ADDRESS: http://configserver:9296
      DB_HOST: mysql
    restart: "no"
    networks:
      - app-tier

  paymentservice:
    build:
      context: ./paymentservice  
    container_name: paymentservice
    depends_on:
      - serviceregistry
      - apigateway
      - authservice
      - configserver
      - mysql
    ports:
      - "8083:8083"
    environment:
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
      CONFIG_SERVER_ADDRESS: http://configserver:9296
      DB_HOST: mysql
    restart: "no"
    networks:
      - app-tier

