server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/dockerdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: optional:configserver:http://localhost:9296


#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10 # buffer size 10
        failure-rate-threshold: 50 #
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true # half open enabled
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10 # record the outcome of calls when the CircuitBreaker is closed
        sliding-window-type: COUNT_BASED # the type of the sliding window

#eureka:

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}